- name: "Destroy infrastructure"
  hosts: localhost
  connection: local 
  gather_facts: no
  vars_files:
  - vars.yaml
  tasks:

  - name: Stop and remove VMs
    community.libvirt.virt:
      command: destroy
      name: '{{ item.name }}'
    with_items: "{{ maszyny }}"
  - community.libvirt.virt:
      command: undefine
      name: '{{ item.name }}'
    with_items: "{{ maszyny }}"

  - name: Delete network
    community.libvirt.virt_net:
      command: destroy
      name: '{{ network_name }}'
  - community.libvirt.virt_net:
      command: undefine
      name: '{{ network_name }}'

