---
# tasks file for k8s_init

- name: Tworzenie klastra
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: init_output
  when: ansible_hostname == main_node
- name: TODO poszukać konfiguracji klastra
  ansible.builtin.debug: var=init_output
  when: ansible_hostname == main_node

- name: Token do połączenia
  ansible.builtin.command: kubeadm token create --print-join-command
  register: join_string
  when: ansible_hostname == main_node
- ansible.builtin.debug: var=join_string.stdout
  when: ansible_hostname == main_node

- name: Podłączenie workerów
  ansible.builtin.command: "{{ hostvars[main_node]['join_string'].stdout }}"
  when: ansible_hostname != main_node

- name: Konfiguracja dla kubectl na węźle głównym
  ansible.builtin.file:
    path: "{{ ansible_env['HOME'] }}/.kube"
    state: directory
    mode: '0700'
  when: ansible_hostname == main_node
- ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ ansible_env['HOME'] }}/.kube/config"
    remote_src: yes
    mode: '0400'
  when: ansible_hostname == main_node
